version: "3"
services:
  core-address:
    image: core-address
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dockercompose
    networks:
      - net-core-address
    depends_on:
      - docker-mysql
      - docker-redis

  docker-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - net-core-address

  docker-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - net-core-address
networks:
  net-core-address: